// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgxpmlasclhbnfeapoor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhneHBtbGFzY2xoYm5mZWFwb29yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NjA4OTMsImV4cCI6MjA3MjQzNjg5M30.rz2EkxR40kmmzMzqzPQx5FvGeLSbhv-5SS8RsCZpmOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});